import { NextRequest, NextResponse } from "next/server";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

export async function GET() {
  try {
    const manifestPath = path.join(process.cwd(), "public", "faces", "opencv_results.json");
    if (fs.existsSync(manifestPath)) {
      const data = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
      return NextResponse.json({ success: true, ...data });
    }
    return NextResponse.json({
      success: true,
      message: "OpenCV pattern matcher ready. Run POST to analyze feeds.",
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    const query = body.query || "Male, approx 5'10\", dark jacket, carrying blue laptop";

    console.log(`[*] Executing OpenCV Pattern Matcher with query: "${query}"`);

    const scriptPath = path.join(process.cwd(), "opencv_pattern_matcher.py");
    const safeQuery = query.replace(/["\\]/g, "");

    // Run OpenCV pattern matcher
    try {
      execSync(`python3 "${scriptPath}" --query "${safeQuery}"`, {
        cwd: process.cwd(),
        timeout: 25000,
        stdio: "pipe",
      });
    } catch (execErr: unknown) {
      console.warn("Python execution warning (checking output):", execErr);
    }

    // Read generated manifest
    const manifestPath = path.join(process.cwd(), "public", "faces", "opencv_results.json");
    if (fs.existsSync(manifestPath)) {
      const data = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
      return NextResponse.json({
        success: true,
        query,
        ...data,
      });
    }

    return NextResponse.json({
      success: false,
      error: "Manifest not generated by OpenCV matcher",
    }, { status: 500 });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
